// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID                    uuid.UUID
	Name                  string
	Value                 float64
	CategoryID            uuid.UUID
	PaymentMethodID       uuid.UUID
	CreditCardID          uuid.UUID
	Status                pgtype.Text
	InstallmentCount      pgtype.Int4
	CurrentInstallment    pgtype.Int4
	InstallmentCountValue pgtype.Float8
	TransactionDate       time.Time
}

type Status struct {
	Name string
}
